### PR TITLE
fix: allow special use domains by default

### LINKED ISSUE #246: 4.1 introduced breaking changes
Our jest environment just started throwing errors because `allowSpecialUseDomain` is now being more enforced in this new release and `jest-environment-jsdom` doesn't set it. I tried to correct for it via Jest's `testEnvironmentOptions` config passthru, but that produced other problems. You may want to revert that release, it's gonna break a WHOLE LOT of builds.

### PR DESCRIPTION
**Pull request by colincasey**
To avoid breaking behavior the `allowSpecialUseDomain` option should have been set to `true` by default.

This PR also adds tests that cover when a default `CookieStore` is created it does allow cookies with special use domains.

closes #246

### CODE REVIEW

File: lib/cookie.js [hunk 1]
```diff
@@ -1099,7 +1099,10 @@ class CookieJar {
     validators.validate(validators.isObject(options), options);
     this.rejectPublicSuffixes = options.rejectPublicSuffixes;
     this.enableLooseMode = !!options.looseMode;
-    this.allowSpecialUseDomain = !!options.allowSpecialUseDomain;
+    this.allowSpecialUseDomain =
+      typeof options.allowSpecialUseDomain === "boolean"
+        ? options.allowSpecialUseDomain
+        : true;
```
Comment (halivert) [inline lib/cookie.js:1105]: Thank you so much for this 🙏🏽

**Review by halivert — APPROVED** [review]
Thanks @colincasey, great work 🎉

**Comment by awaterma** [comment]
Looks good to me as well @colincasey; nice to see a fix that makes a change and adds a test. :) 

I've also hand-checked straight localhost creation:

```
cookie@d8759915569c:~$ node 
Welcome to Node.js v16.17.0.
Type ".help" for more information.
> const Cookie = require(".")
undefined
> jar = new Cookie.CookieJar();
CookieJar {
  rejectPublicSuffixes: true,
  enableLooseMode: false,
  allowSpecialUseDomain: true,
  store: { idx: {} },
  prefixSecurity: 'silent',
  _cloneSync: [Function (anonymous)],
  _importCookiesSync: [Function (anonymous)],
  getCookiesSync: [Function (anonymous)],
  getCookieStringSync: [Function (anonymous)],
  getSetCookieStringsSync: [Function (anonymous)],
  removeAllCookiesSync: [Function (anonymous)],
  setCookieSync: [Function (anonymous)],
  serializeSync: [Function (anonymous)]
}
> await(jar.setCookie('settingThisShouldPass=true,Domain=localhost; Path="/;"','http://localhost'))
Cookie="settingThisShouldPass=true,Domain=localhost; Path=/; "; hostOnly=true; aAge=1ms; cAge=1ms"
```

**Review by awaterma — APPROVED** [review]
Approved

**Review by bartgriffith — APPROVED** [review]

**Comment by CSchulz** [comment]
This doesn't close #246 completly, because there is still the breaking change mentioned in #248 contained.
If you are using localhost as test environment url it is not enough, you have to change it to localhost.local.

**Comment by Sourav-techlur** [comment]
Hey @awaterma I am still having the same issue with v4.1.1.
